"""All ICA Maxi stores in Sweden — with proper Swedish characters."""

STORE_REGISTRY = {
    "ica-maxi-1003647": {"name": "Maxi ICA Stormarknad Alingsås", "city": "Alingsås", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-alingsas-1003647/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004494": {"name": "Maxi ICA Stormarknad Angered", "city": "Angered", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-angered-1004494/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1131004": {"name": "Maxi ICA Stormarknad Arninge", "city": "Arninge", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-arninge-1131004/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1166011": {"name": "Maxi ICA Stormarknad Arvika", "city": "Arvika", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-arvika-1166011/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003408": {"name": "Maxi ICA Stormarknad Barkarbystaden", "city": "Barkarbystaden", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-barkarbystaden-1003408/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1051012": {"name": "Maxi ICA Stormarknad Bollnäs", "city": "Bollnäs", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-bollnas-1051012/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004119": {"name": "Maxi ICA Stormarknad Borlänge", "city": "Borlänge", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-borlange-1004119/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003722": {"name": "Maxi ICA Stormarknad Borås", "city": "Borås", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-boras-1003722/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004407": {"name": "Maxi ICA Stormarknad Botkyrka", "city": "Botkyrka", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-botkyrka-1004407/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1015001": {"name": "Maxi ICA Stormarknad Bromma", "city": "Bromma", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-bromma-1015001/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003838": {"name": "Maxi ICA Stormarknad Bromölla", "city": "Bromölla", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-bromolla-1003838/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1158001": {"name": "Maxi ICA Stormarknad Brynäs", "city": "Brynäs", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-brynas-1158001/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003428": {"name": "Maxi ICA Stormarknad Burlöv", "city": "Burlöv", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-burlov-1003428/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003429": {"name": "Maxi ICA Stormarknad Bålsta", "city": "Bålsta", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-balsta-1003429/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004380": {"name": "Maxi ICA Stormarknad Enköping", "city": "Enköping", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-enkoping-1004380/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004187": {"name": "Maxi ICA Stormarknad Erikslund", "city": "Erikslund", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-erikslund-1004187/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004513": {"name": "Maxi ICA Stormarknad Eskilstuna", "city": "Eskilstuna", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-eskilstuna-1004513/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003410": {"name": "Maxi ICA Stormarknad Falköping", "city": "Falköping", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-falkoping-1003410/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003411": {"name": "Maxi ICA Stormarknad Falun", "city": "Falun", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-falun-1003411/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003430": {"name": "Maxi ICA Stormarknad Flemingsberg", "city": "Flemingsberg", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-flemingsberg-1003430/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003781": {"name": "Maxi ICA Stormarknad Flygstaden", "city": "Flygstaden", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-flygstaden-1003781/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003431": {"name": "Maxi ICA Stormarknad Gnista Uppsala", "city": "Gnista Uppsala", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-gnista-uppsala-1003431/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1088004": {"name": "Maxi ICA Stormarknad Gunnesbo Lund", "city": "Gunnesbo Lund", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-gunnesbo-lund-1088004/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003987": {"name": "Maxi ICA Stormarknad Gävle", "city": "Gävle", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-gavle-1003987/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004219": {"name": "Maxi ICA Stormarknad Göteborg", "city": "Göteborg", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-goteborg-1004219/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003777": {"name": "Maxi ICA Stormarknad Haninge", "city": "Haninge", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-haninge-1003777/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003413": {"name": "Maxi ICA Stormarknad Haparanda", "city": "Haparanda", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-haparanda-1003413/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004084": {"name": "Maxi ICA Stormarknad Helsingborg", "city": "Helsingborg", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-helsingborg-1004084/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003414": {"name": "Maxi ICA Stormarknad Hudiksvall", "city": "Hudiksvall", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-hudiksvall-1003414/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003937": {"name": "Maxi ICA Stormarknad Hyllinge", "city": "Hyllinge", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-hyllinge-1003937/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003415": {"name": "Maxi ICA Stormarknad Häggvik", "city": "Häggvik", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-haggvik-1003415/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003947": {"name": "Maxi ICA Stormarknad Hälla", "city": "Hälla", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-halla-1003947/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003949": {"name": "Maxi ICA Stormarknad Härnösand", "city": "Härnösand", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-harnosand-1003949/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003545": {"name": "Maxi ICA Stormarknad Hässleholm", "city": "Hässleholm", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-hassleholm-1003545/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003954": {"name": "Maxi ICA Stormarknad Högsbo, Göteborg", "city": "Högsbo, Göteborg", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-hogsbo-1003954/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003925": {"name": "Maxi ICA Stormarknad Högskolan", "city": "Högskolan", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-hogskolan-1003925/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004015": {"name": "Maxi ICA Stormarknad Jönköping", "city": "Jönköping", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-jonkoping-1004015/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004348": {"name": "Maxi ICA Stormarknad Kalmar", "city": "Kalmar", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-kalmar-1004348/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004027": {"name": "Maxi ICA Stormarknad Karlshamn", "city": "Karlshamn", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-karlshamn-1004027/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004704": {"name": "Maxi ICA Stormarknad Karlskoga", "city": "Karlskoga", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-karlskoga-1004704/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004028": {"name": "Maxi ICA Stormarknad Karlskrona", "city": "Karlskrona", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-karlskrona-1004028/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004029": {"name": "Maxi ICA Stormarknad Karlstad", "city": "Karlstad", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-karlstad-1004029/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004034": {"name": "Maxi ICA Stormarknad Katrineholm", "city": "Katrineholm", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-katrineholm-1004034/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004057": {"name": "Maxi ICA Stormarknad Kristianstad", "city": "Kristianstad", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-kristianstad-1004057/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004299": {"name": "Maxi ICA Stormarknad Kristinehamn", "city": "Kristinehamn", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-kristinehamn-1004299/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003562": {"name": "Maxi ICA Stormarknad Kumla", "city": "Kumla", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-kumla-1003562/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004185": {"name": "Maxi ICA Stormarknad Kungsbacka", "city": "Kungsbacka", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-kungsbacka-1004185/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004392": {"name": "Maxi ICA Stormarknad Kungälv", "city": "Kungälv", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-kungalv-1004392/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004375": {"name": "Maxi ICA Stormarknad Köping", "city": "Köping", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-koping-1004375/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1156008": {"name": "Maxi ICA Stormarknad Landskrona", "city": "Landskrona", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-landskrona-1156008/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003418": {"name": "Maxi ICA Stormarknad Lindhagen", "city": "Lindhagen", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-lindhagen-1003418/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003823": {"name": "Maxi ICA Stormarknad Linköping", "city": "Linköping", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-linkoping-1003823/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004102": {"name": "Maxi ICA Stormarknad Ljungby", "city": "Ljungby", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-ljungby-1004102/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003382": {"name": "Maxi ICA Stormarknad Luleå", "city": "Luleå", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-lulea-1003382/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004060": {"name": "Maxi ICA Stormarknad Löddeköpinge", "city": "Löddeköpinge", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-loddekopinge-1004060/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004492": {"name": "Maxi ICA Stormarknad Malmö", "city": "Malmö", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-malmo-1004492/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004243": {"name": "Maxi ICA Stormarknad Mellbystrand", "city": "Mellbystrand", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-mellbystrand-1004243/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003419": {"name": "Maxi ICA Stormarknad Mora", "city": "Mora", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-mora-1003419/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003735": {"name": "Maxi ICA Stormarknad Mora", "city": "Mora", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-moraberg-1003735/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004267": {"name": "Maxi ICA Stormarknad Motala", "city": "Motala", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-motala-1004267/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004282": {"name": "Maxi ICA Stormarknad Nacka", "city": "Nacka", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-nacka-1004282/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1051010": {"name": "Maxi ICA Stormarknad Norrköping", "city": "Norrköping", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-norrkoping-1051010/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004303": {"name": "Maxi ICA Stormarknad Nyköping", "city": "Nyköping", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-nykoping-1004303/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003421": {"name": "Maxi ICA Stormarknad Nynäshamn", "city": "Nynäshamn", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-nynashamn-1003421/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004346": {"name": "Maxi ICA Stormarknad Olofström", "city": "Olofström", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-olofstrom-1004346/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004340": {"name": "Maxi ICA Stormarknad Oskarshamn", "city": "Oskarshamn", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-oskarshamn-1004340/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004365": {"name": "Maxi ICA Stormarknad Partille", "city": "Partille", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-partille-1004365/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003513": {"name": "Maxi ICA Stormarknad Ronneby", "city": "Ronneby", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-ronneby-1003513/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003916": {"name": "Maxi ICA Stormarknad Råå Helsingborg", "city": "Råå Helsingborg", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-raa-1003916/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003396": {"name": "Maxi ICA Stormarknad Sandviken", "city": "Sandviken", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-sandviken-1003396/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003910": {"name": "Maxi ICA Stormarknad Skellefteå", "city": "Skellefteå", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-skelleftea-1003910/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004080": {"name": "Maxi ICA Stormarknad Skövde", "city": "Skövde", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-skovde-1004080/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003380": {"name": "Maxi ICA Stormarknad Solna", "city": "Solna", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-solna-1003380/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004488": {"name": "Maxi ICA Stormarknad Stenhagen Uppsala", "city": "Stenhagen Uppsala", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-stenhagen-uppsala-1004488/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003423": {"name": "Maxi ICA Stormarknad Sundsvall", "city": "Sundsvall", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-sundsvall-1003423/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1106003": {"name": "Maxi ICA Stormarknad Söderhamn", "city": "Söderhamn", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-soderhamn-1106003/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003807": {"name": "Maxi ICA Stormarknad Toftanäs", "city": "Toftanäs", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-toftanas-1003807/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003825": {"name": "Maxi ICA Stormarknad Torslanda", "city": "Torslanda", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-torslanda-1003825/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003620": {"name": "Maxi ICA Stormarknad Trelleborg", "city": "Trelleborg", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-trelleborg-1003620/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003604": {"name": "Maxi ICA Stormarknad Trollhättan", "city": "Trollhättan", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-trollhattan-1003604/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003734": {"name": "Maxi ICA Stormarknad Ulricehamn", "city": "Ulricehamn", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-ulricehamn-1003734/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003828": {"name": "Maxi ICA Stormarknad Umeå", "city": "Umeå", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-umea-1003828/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003736": {"name": "Maxi ICA Stormarknad Universitetet", "city": "Universitetet", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-universitetet-1003736/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004109": {"name": "Maxi ICA Stormarknad Vasa Handelsplats", "city": "Vasa Handelsplats", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-vasa-handelsplats-1004109/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003555": {"name": "Maxi ICA Stormarknad Vetlanda", "city": "Vetlanda", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-vetlanda-1003555/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003730": {"name": "Maxi ICA Stormarknad Visby", "city": "Visby", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-visby-1003730/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003565": {"name": "Maxi ICA Stormarknad Välsviken", "city": "Välsviken", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-valsviken-1003565/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003424": {"name": "Maxi ICA Stormarknad Värmdö", "city": "Värmdö", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-varmdo-1003424/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003568": {"name": "Maxi ICA Stormarknad Västervik", "city": "Västervik", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-vastervik-1003568/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003569": {"name": "Maxi ICA Stormarknad Västra Hamnen", "city": "Västra Hamnen", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-vastra-hamnen-1003569/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003571": {"name": "Maxi ICA Stormarknad Växjö", "city": "Växjö", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-vaxjo-1003571/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003525": {"name": "Maxi ICA Stormarknad Älmhult", "city": "Älmhult", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-almhult-1003525/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003594": {"name": "Maxi ICA Stormarknad Ängelholm", "city": "Ängelholm", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-angelholm-1003594/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1004097": {"name": "Maxi ICA Stormarknad Örebro Boglundsängen", "city": "Örebro Boglundsängen", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-orebro-boglundsangen-1004097/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1003733": {"name": "Maxi ICA Stormarknad Östersund", "city": "Östersund", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-ostersund-1003733/", "scraper_class": "IcaMaxiScraper"},
    "ica-maxi-1051011": {"name": "Maxi ICA Stormarknad Österåker", "city": "Österåker", "url": "https://www.ica.se/erbjudanden/maxi-ica-stormarknad-osteraker-1051011/", "scraper_class": "IcaMaxiScraper"},
}